//
//  Ovens.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//

import Foundation
import UIKit
import AWSDynamoDB

class DBOven: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _timestamp: String?
    var _creatorName: String?
    var _difficulty: NSNumber?
    var _id: String?
    var _name: String?
    var _numberOfPictures: NSNumber?
    var _ovenType: String?
    var _parts: Set<String>?
    var _steps: Set<String>?
    
    class func dynamoDBTableName() -> String {
        
        return "solarrecipes-mobilehub-623139932-Ovens"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_timestamp"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_timestamp" : "timestamp",
            "_creatorName" : "creatorName",
            "_difficulty" : "difficulty",
            "_id" : "id",
            "_name" : "name",
            "_numberOfPictures" : "numberOfPictures",
            "_ovenType" : "ovenType",
            "_parts" : "parts",
            "_steps" : "steps",
        ]
    }
}
