//
//  Recipe.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.12
//

import Foundation
import UIKit
import AWSDynamoDB

class DBRecipe: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _id: String?
    var _name: String?
    var _creatorFBID: String?
    var _creatorName: String?
    var _description: String?
    var _difficulty: NSNumber?
    var _duration: NSNumber?
    var _toDuration: NSNumber?
    var _ingredients: Set<String>?
    var _instructions: Set<String>?
    var _comments: Set<String>?
    var _numberOfPictures: NSNumber?
    var _temperature: NSNumber?
    var _toTemperature: NSNumber?
    var _timestamp: String?
    var _ovenType: String?
    
    class func dynamoDBTableName() -> String {
        
        return "solarrecipes-mobilehub-623139932-Recipe"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_id"
    }
    
    class func rangeKeyAttribute() -> String {
        
        return "_name"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_id" : "id",
            "_name" : "name",
            "_creatorFBID" : "creatorFBID",
            "_creatorName" : "creatorName",
            "_description" : "description",
            "_difficulty" : "difficulty",
            "_duration" : "duration",
            "_toDuration" : "toDuration",
            "_ingredients" : "ingredients",
            "_instructions" : "instructions",
            "_numberOfPictures" : "numberOfPictures",
            "_toTemperature" : "toTemperature",
            "_temperature" : "temperature",
            "_timestamp" : "timestamp",
            "_comments" : "comments",
            "_ovenType" : "ovenType",
        ]
    }
}
